export const GET_USER_SETTINGS = "GET_USER_SETTINGS";
export const SET_USER_SETTINGS = "SET_USER_SETTINGS";
export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";
export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const SIGN_IN_USER = "SIGN_IN_USER";

export const FETCH_DARES_ADMIN = "FETCH_DARES_ADMIN";

export const FETCH_DARE_BEGIN   = 'FETCH_DARE_BEGIN';
export const FETCH_DARE_SUCCESS = 'FETCH_DARE_SUCCESS';
export const FETCH_DARE_FAILURE = 'FETCH_DARE_FAILURE';
export const CLEAR_DARE = 'CLEAR_DARE';

export const FETCH_DARES_BEGIN   = 'FETCH_DARES_BEGIN';
export const FETCH_DARES_SUCCESS = 'FETCH_DARES_SUCCESS';
export const FETCH_DARELIST_SUCCESS = 'FETCH_DARELIST_SUCCESS';
export const FETCH_DARES_FAILURE = 'FETCH_DARES_FAILURE';

export const FETCH_ENTRY_BEGIN   = 'FETCH_ENTRY_BEGIN';
export const FETCH_ENTRY_SUCCESS = 'FETCH_ENTRY_SUCCESS';
export const FETCH_ENTRY_FAILURE = 'FETCH_ENTRY_FAILURE';
export const CLEAR_ENTRY = 'CLEAR_ENTRY';

export const FETCH_ENTRIES_BEGIN   = 'FETCH_ENTRIES_BEGIN';
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE';

export const FETCH_DURRAN_USER_BEGIN = 'FETCH_DURRAN_USER_BEGIN';
export const FETCH_DURRAN_USER_SUCCESS = 'FETCH_DURRAN_USER_SUCCESS';
export const FETCH_DURRAN_USER_FAILURE = 'FETCH_DURRAN_USER_FAILURE';
export const CLEAR_DURRAN_USER = 'CLEAR_DURRAN_USER';
